---

- hosts: prod_shc
  become: yes
  vars:
    user: splunk_localuser
    user_group: wheel
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
    yum_packages:
      - { name: 'sysstat'}
  roles:
    - yum_install-os-apps
