---

- hosts: showcase_cap
  sudo: yes
  vars:
    user: splunk_localuser
    user_group: wheel
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
    cluster_members: ""
  roles:
    - splunk_shc_cap_election
