---

- hosts: prod_idx_cm
  vars:
    user: splunk_localuser
    user_group: wheel
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
    deploy_dir: master-apps
    app_packages:
      - { project: 'zero-cm', repo: 'index_apps', branch: 'master'}
      #- { project: 'zero-id', repo: 'zero_prod', branch: 'master'}
      - { project: 'zero-id', repo: '01-gold_idx', branch: 'master'}
      # splunkbase applications
      - { project: 'zero-sb', repo: 'ta-fire_brigade', branch: 'master'}
      - { project: 'zero-sb', repo: 'analysis_of_splunkbase_apps', branch: 'IDX'}
      # apps developed by other teams in splunk
      - { project: 'zero-ed', repo: 'ta-skynet', branch: 'master'}
  roles:
    - configure_host_vars
    - configure_git-management
    - { role: splunk_idx_update-group-apps, when: result is changed }
    - { role: splunk_gen_update-repo-apps, when: result is changed }
    - { role: splunk_idx_enable_main, when: result is changed }
    - { role: splunk_idx-cm_app-deploy, when: result is changed }
