---

- hosts: stage_idx
  serial: 10
  become: yes
  vars:
    splunk_user: splunk
    user: splunk_localuser
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
  roles:
    - splunk_gen_restart