---

- hosts: itsi_apl
  vars:
    user: splunk_localuser
    user_group: wheel
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
# application deployment variables
    deploy_dir: shcluster/apps
    app_packages:
      - { project: 'zero-cm', repo: 'itsi_package', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_prod', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_dsa', branch: 'df_changes'}
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master'}
      - { project: 'zero-id', repo: '01-rolemap_itsi', branch: 'master'}
      - { project: 'zero-id', repo: '01-rolemap_perm', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'master'}
      - { project: 'zero-id', repo: 'splunk_it', branch: 'master'}
      - { project: 'zero-ed', repo: 'google_drive', branch: 'master'}
#    app_decom:
#      - { project: 'zero-id', repo: 'zero_dsa' }
#    app_backup:
#      - { project: 'zero-cm', repo: 'shc-apps', branch: 'backup' }
#    message: backup
  roles:
    - configure_host_vars
    - configure_git-management
#    - { role: splunk_gen_backup-local }
#    - { role: splunk_shc_update-group-apps, when: result|changed }
    - { role: splunk_gen_update-repo-apps, when: result|changed }
#    - { role: splunk_gen_decom-apps, when: result|changed }
    - splunk_shc_app_deploy
