---

- hosts: stage_mon
  vars:
    user: splunk_localuser
    user_group: wheel
    ansible_user: splunk_localuser
    ansible_ssh_private_key_file: ~/.ssh/splunk-server-ssh.key
    okta_chic_key: '{{ okta }}'
#    uri: configured in host file
  become: yes
  roles:
    - splunk_gen_conf_auth-saml
