---

- name: remove git checkouts
  file:
    path: '{{ clone_path }}'
    state: absent
  become: yes

- name: verify git directory
  file:
    path: '{{ clone_path }}'
    owner: splunk
    group: splunk
    state: directory
    mode: 0777
  become: yes

#- name: verify clean directory
#  become: yes
#  shell: rm -rf {{ splunk_home }}/repo
#  ignore_errors: yes

#- name: make clone directory
#  become: yes
#  command: mkdir {{ splunk_home }}/repo/

#- name: set owner
#  become: yes
#  command: chown splunk:splunk {{ splunk_home }}/repo/

#- name: set perms
#  become: yes
#  command: chmod 777 {{ splunk_home }}/repo/
